@@include('../libs/jquery/jquery.js')
@@include('../libs/uikit3/uikit.min.js') 
@@include('../libs/uikit3/uikit-icons.min.js')
@@include('../libs/lightgallery/lightgallery-all.js')
@@include('../libs/macy/macy.js')
